# Generated by Django 4.2 on 2023-04-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='puntitotali',
            field=models.IntegerField(null=True),
        ),
    ]
