# Generated by Django 4.2 on 2023-04-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_puntitotali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='puntitotali',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
