# Generated by Django 4.2 on 2023-04-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_puntitotali'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sfide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfide', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
