# Generated by Django 4.2 on 2023-04-27 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sfide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sfide',
            old_name='sfide',
            new_name='sfida',
        ),
    ]
