# Generated by Django 4.2 on 2023-04-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_sfide_sfide_sfida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sfide',
        ),
        migrations.AddField(
            model_name='profile',
            name='sfide',
            field=models.ManyToManyField(to='accounts.sfide'),
        ),
    ]
