# Generated by Django 4.2 on 2023-04-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_sfide'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfide',
            name='punti',
            field=models.IntegerField(default='0'),
        ),
    ]
